const { Schema, model } = require("mongoose");

const ShortlySchema = new Schema(
  {
    shortlyId: { type: String, required: true, unique: true },
    purpose: { type: String, required: true },
    subscriptionId: { type: Schema.Types.ObjectId, ref: "subscriptions" },
    status: { type: Number, default: 10 },
    paymentStatus: { type: String, default: "pending" }, // pending, failed, success
    receiptNumber: { type: String },
    spaceNumber: { type: String },
    brandLogo: { type: String },
    clientSecretACH: { type: String },
    clientSecretGenerateCount: { type: Number, default: 0 },
    hours: { type: Number, default: 0 },
    expireOn: { type: Date, default: null },
    extensionExpireOn: { type: Date, default: null },
    isSecondStepValidationRate: { type: Boolean, default: false },
    isPayNowValidationLaterFlow: { type: Boolean, default: false },
    isExtension: { type: Boolean, default: false },
    isFromSMS: { type: Boolean, default: false },
    isParking: { type: Boolean, default: false },
    rateId: { type: Schema.Types.ObjectId, ref: "rates" },
    placeId: { type: Schema.Types.ObjectId, ref: "places" },
    brandId: { type: Schema.Types.ObjectId, ref: "brands" },
    customerId: { type: Schema.Types.ObjectId, ref: "customers" },
    isApplyTax: { type: Boolean, default: false },
    isApplyServiceFee: { type: Boolean, default: false },
    isApplyTaxOnServiceFee: { type: Boolean, default: false },
    paymentGatewayFeePayBy: { type: String, default: "spotsync" },
    taxPercentage: { type: Number, default: 0 },
    cityTaxPercentage: { type: Number, default: 0 },
    countyTaxPercentage: { type: Number, default: 0 },
    totalAmount: { type: Number, default: 0 },
    ownerPayout: { type: Number, default: 0 },
    spotsyncRevenue: { type: Number, default: 0 },
    applicationFee: { type: Number, default: 0 },
    paymentGatewayFee: { type: Number, default: 0 },
    baseRate: { type: Number, default: 0 },
    tax: { type: Number, default: 0 },
    cityTax: { type: Number, default: 0 },
    countyTax: { type: Number, default: 0 },
    serviceFee: { type: Number, default: 0 },
    licensePlate: { type: String },
    receiptURL: { type: String },
    phoneNumber: { type: String },
    transientNumber: { type: String },
    paymentMethodId: { type: String },
    paymentMethodType: { type: String },
    sessionId: { type: Schema.Types.ObjectId, ref: "sessions" },
    paymentId: { type: Schema.Types.ObjectId, ref: "payments" },
    reservationId: { type: Schema.Types.ObjectId, ref: "reservations" },
    validationId: { type: Schema.Types.ObjectId, ref: "validations" },
    discountPercentage: { type: Number, default: 0 },
    validationCode: { type: String },
    transactionId: { type: String },
    isValidationApplied: { type: Boolean, default: false },
    isMonthlyReservation: { type: Boolean, default: false },
    withoutDiscounted: {},
    validations: [],
    transactionDate: { type: Date },
    gracePeriodExpirationDate: { type: Date },
    noOfPasses: { type: Number, default: 1 },
    email: { type: String, default: "" },
    isPass: { type: Boolean, default: false },
    lastName: { type: String, default: "" },
    createdAt: { type: Date, default: new Date() },
    updatedAt: { type: Date, default: new Date() },
  },
  { timestamps: true }
);

module.exports = Shortly = model("shortlies", ShortlySchema);
